pipeline {

    agent any
 
    tools {

        maven 'Maven 3.8.1'  // Use the Maven version configured in Jenkins

        jdk 'jdk-21'          // Use the JDK version configured in Jenkins

    }
 
    stages {

        stage('Checkout') {

            steps {

                // Checkout the entire repo

                git branch: 'main', url: 'https://github.com/KomalRethi/Day-2025-10-15.git'

            }

        }
 
        stage('Build') {

            steps {

                // Change directory to MyGitTest before running Maven commands

                bat 'cd SBwithH2db && mvn clean compile'

            }

        }
 
        stage('Test') {

            steps {

                bat 'cd SBwithH2db && mvn test'

            }

        }
 
        stage('Package') {

            steps {

                bat 'cd SBwithH2db && mvn package'

            }

        }
 
    }

}

 
